### ISSUE TITLE
TODO lists

### ISSUE THREAD

**Issue by iory** [iory/scikit-robot#3]
- [x] Add document **everyone**
- [x] Update inverse kinematics (nullspace + additional_jacobian) @iory 
- [x] Refactoring code @iory 
- [x] OpenGL viewer (trimesh + urdfpy) @wkentaro 
- [x] Collision check (trimesh) @wkentaro 
- [x] Create demo @iory -> https://github.com/iory/scikit-robot?tab=readme-ov-file#features
